---

spring:
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.config-repo.credentials.uri}
         
security:
  user:
    name: username
    password: password